# GT4Py - GridTools Framework
#
# Copyright (c) 2014-2024, ETH Zurich
# All rights reserved.
#
# Please, refer to the LICENSE file in the root directory.
# SPDX-License-Identifier: BSD-3-Clause

from __future__ import annotations

import dataclasses
from typing import Any, Literal, Mapping, Optional, Sequence, Union, overload

import numpy as np

from gt4py.next import common as gtx_common
from gt4py.next.iterator import ir
from gt4py.next.otf import code_specs, stages
from gt4py.next.program_processors.runners.dace.workflow import common as gtx_wfdcommon
from gt4py.next.type_system import type_specifications as ts


def argument_processing_function(
    args: tuple[Any, ...],
    offset_provider: gtx_common.OffsetProvider,
    metrics_level: int,
    runtime_return_value: Any,
) -> Any:
    """Signature generated by `_create_sdfg_bindings()` and used to process the arguments for an SDFG call.

    See `_create_sdfg_bindings()` and `bind_sdfg()` for more.

    Args:
        args: The arguments that are passed to the SDFG. A tuple of fields and nested tuples.
        offset_provider: The offset providers (order is used verbatim).
        metrics_level: The level of the metric that is active.
        runtime_return_value: NumPy array used to write back the runtime spend in the call.
    """
    raise NotImplementedError("`argument_processing_function()` is only for documenting purposes.`")


def _create_sdfg_bindings(
    prog: ir.Program,
    offset_provider_type: gtx_common.OffsetProviderType,
    bind_func_name: str,
    use_metrics: bool,
    eval_mode: bool,
    backend: Literal["gtfn", "dace"],
) -> str:
    """
    Creates a Python function that translates GT4Py arguments into arguments suitable for a SDFG call.

    The returned string can be passed to exec to then dynamically create a function to
    perform the translation. The function will have the same signature as
    `argument_processing_function()` and have the name `bind_func_name`.
    The translation function targets the `user_args` interface of the SDFG.

    The function has experimental support for GTFN. Furthermore, it is also possible
    to create only a dispatch function, i.e. the returned function only forwards the
    processing to an actual function. This is only useful for debugging.

    Args:
        prog: The program definition.
        offset_provider_type: The offset provider types.
        bind_func_name: The name of the function to perform the translation.
        use_metrics: If metric support was added to the underlying compiled code.
            In that case the last two arguments of the generated function signature
            are ignored and also not included in the output.
        eval_mode: If `False` the generated function will dispatch to a real Python
            function that performs the processing instead of a function that is fully
            code generated.
        backend: For which backend the generated function should be used.
    """
    assert backend in ["gtfn", "dace"]

    code_lines: list[str] = []
    if eval_mode:
        code_lines.append(
            "from gt4py.next.program_processors.runners.dace.workflow import nanobinings as gtx_wfdnanobindings"
        )

    code_lines.append(f"def {bind_func_name}(")
    code_lines.append("\targs,")
    code_lines.append("\toffset_provider,")
    code_lines.append(f"\t{gtx_wfdcommon.SDFG_ARG_METRIC_LEVEL},")
    code_lines.append(f"\t{gtx_wfdcommon.SDFG_ARG_METRIC_COMPUTE_TIME},")
    code_lines.append("):")

    if eval_mode:
        code_lines.append("\treturn gtx_wfdnanobindings._perform_argument_processing(")
        code_lines.append("\t\targs=args,")
        code_lines.append("\t\toffset_provider=offset_provider,")
        code_lines.append(f"\t\tmetric_level={gtx_wfdcommon.SDFG_ARG_METRIC_LEVEL},")
        code_lines.append(f"\t\truntime_return_value={gtx_wfdcommon.SDFG_ARG_METRIC_COMPUTE_TIME},")
        code_lines.append(f"\t\tuse_metrics={use_metrics},")
        code_lines.append(f"\t\tbackend='{backend}',")
        code_lines.append("\t)")

    else:
        expanded_args: list[str] = [f"__gtx_expanded_names_{param.id}" for param in prog.params]
        unpacked_variables: list[str] = [", ".join(expanded_args) + ", = args"]
        process_arg_stmt = ""
        for arg_name, param in zip(expanded_args, prog.params):
            assert param.type is not None
            process_arg_stmt += _process_argument(
                argument=arg_name,
                param_type=param.type,
                unpacked_variables=unpacked_variables,
                backend=backend,
            )
            assert process_arg_stmt.strip().endswith(",")
        assert process_arg_stmt.strip().endswith(",")
        process_arg_stmt += _process_offset_providers(  # type: ignore[operator]
            offset_provider=offset_provider_type, eval_mode=False
        )
        process_arg_stmt += _process_metric_arguments(
            metric_level=gtx_wfdcommon.SDFG_ARG_METRIC_LEVEL,
            compute_time_argument=gtx_wfdcommon.SDFG_ARG_METRIC_COMPUTE_TIME,
            eval_mode=False,
            backend=backend,
            use_metrics=use_metrics,
        )
        code_lines.extend(("\t" + s for s in unpacked_variables))
        code_lines.append(f"\treturn ({process_arg_stmt})")

    return "\n".join(code_lines)


def bind_sdfg(
    inp: stages.ProgramSource[code_specs.SDFGCodeSpec],
    bind_func_name: str,
) -> stages.ExtensionSource[code_specs.SDFGCodeSpec, code_specs.PythonCodeSpec]:
    """
    Method to be used as workflow stage for generation of SDFG bindings.

    Refer to `_create_sdfg_bindings()` documentation.
    """
    # NOTE: This function should actually call `_create_sdfg_bindings()` however,
    #   not all necessarily arguments are present here. For that reason they are
    #   generated by `DaCeTranslator.__call__()` and we just process them a little
    #   bit further.
    assert isinstance(inp.source_code, tuple) and len(inp.source_code) == 2

    source_code: tuple[str, dict] = inp.source_code
    binding_code_generated_during_translation, jsdfg = source_code
    assert f"def {bind_func_name}(" in binding_code_generated_during_translation

    program_source = dataclasses.replace(inp, source_code=jsdfg)
    binding_source = stages.BindingSource(
        binding_code_generated_during_translation, library_deps=tuple()
    )

    return stages.ExtensionSource(
        program_source=program_source,
        binding_source=binding_source,
    )


@overload
def _perfom_tuple_unpacking(
    tuple_argument: tuple[Any, ...],
    tuple_len: int,
    unpacked_variables: None,
) -> tuple[Any, ...]: ...


@overload
def _perfom_tuple_unpacking(
    tuple_argument: str,
    tuple_len: int,
    unpacked_variables: list[str],
) -> list[str]: ...


def _perfom_tuple_unpacking(
    tuple_argument: Union[tuple[Any, ...], str],
    tuple_len: int,
    unpacked_variables: Optional[list[str]],
) -> Union[tuple[Any, ...], list[str]]:
    if unpacked_variables is None:
        # Eval mode: Simply unpack the tuple.
        assert isinstance(tuple_argument, tuple) and len(tuple_argument) == tuple_len
        return tuple_argument
    else:
        # Generation mode: Write a line that performs the unpacking and adds it to
        #   `unpacked_variables` and return their names.
        assert isinstance(tuple_argument, str) and len(tuple_argument) > 0
        unpacked_arguments = [f"{tuple_argument}_{i}" for i in range(tuple_len)]
        unpacked_variables.append(f"{', '.join(unpacked_arguments)}, = {tuple_argument}")
        return unpacked_arguments


@overload
def _process_argument(
    argument: Any,
    param_type: None,
    unpacked_variables: None,
    backend: Literal["gtfn", "dace"],
) -> tuple[Any, ...]: ...


@overload
def _process_argument(
    argument: str,
    param_type: ts.TypeSpec,
    unpacked_variables: list[str],
    backend: Literal["gtfn", "dace"],
) -> str: ...


def _process_argument(
    argument: Union[Any, str],
    param_type: Optional[ts.TypeSpec],
    unpacked_variables: Optional[list[str]],
    backend: Literal["gtfn", "dace"],
) -> Union[tuple[Any, ...], str]:

    tuple_types: Optional[Sequence[Any]]
    if unpacked_variables is None:
        assert param_type is None
        eval_mode = True
        is_field = hasattr(argument, "__gt_origin__")
        is_scalar = True  # No other choice
        is_bool = isinstance(argument, (np.bool_, bool))
        tuple_types = (None,) * len(argument) if (is_tuple := isinstance(argument, tuple)) else None

    else:
        assert param_type is not None
        eval_mode = False
        is_field = isinstance(param_type, ts.FieldType)
        is_scalar = isinstance(param_type, ts.ScalarType)
        is_bool = param_type.kind == ts.ScalarKind.BOOL if is_scalar else False  # type: ignore[attr-defined]
        tuple_types = (
            param_type.types if (is_tuple := isinstance(param_type, ts.TupleType)) else None
        )

    if is_tuple:
        assert tuple_types is not None and isinstance(argument, tuple)  # Make MyPy happy
        tuple_members = _perfom_tuple_unpacking(argument, len(tuple_types), unpacked_variables)  # type: ignore[arg-type]
        processed_tuple_members: Union[str, tuple[Any, ...]] = tuple() if eval_mode else "("
        for tuple_member, tuple_member_type in zip(tuple_members, tuple_types):
            processed_tuple_members += _process_argument(  # type: ignore[operator]
                argument=tuple_member,
                param_type=tuple_member_type,  # type: ignore[arg-type]
                unpacked_variables=unpacked_variables,  # type: ignore[arg-type]
                backend=backend,
            )

        # The trailing commas are intentionally and are needed for symmetry reasons. See
        #  also the note in `_perform_argument_processing()`.
        return (processed_tuple_members,) if eval_mode else (processed_tuple_members + "),")  # type: ignore[operator]

    command: str
    if is_field:
        argument_name = "argument" if eval_mode else argument
        if (len(argument.domain) == 0) if eval_mode else (len(param_type.dims) == 0):  # type: ignore[union-attr]
            # GTFN wants a field, dace a scalar.
            command = f"{argument_name}" if backend == "gtfn" else f"{argument_name}.as_scalar()"
        else:
            # Full array, the differences is where the origin comes from.
            origin_prop = "__gt_origin__" if backend == "gtfn" else "__dace_origin__"
            command = f"({argument_name}.ndarray, ({argument_name}.{origin_prop}))"

    elif is_scalar:
        command = "{cast}({arg})".format(
            arg="argument" if eval_mode else argument,
            cast=("bool" if is_bool and backend == "gtfn" else ""),
        )
    else:
        assert isinstance(argument, str)
        raise ValueError(f"Parameter `{argument}` had unexpected type `{param_type}`")

    command += ", "  # Comma is intentional.
    return eval(command) if eval_mode else command


def _process_offset_providers(
    offset_provider: Union[gtx_common.OffsetProvider, gtx_common.OffsetProviderType],
    eval_mode: bool,
) -> Union[str, tuple[Any, ...]]:
    # Assumes that the order of the offset providers is stable.
    # And that there is no difference between GTFN and DaCe
    processed_offset_providers: Union[str, tuple[Any, ...]] = tuple() if eval_mode else ""
    for table_name in offset_provider:
        command = f"(offset_provider['{table_name}'].ndarray, (0, 0)), "
        processed_offset_providers += eval(command) if eval_mode else command  # type: ignore[operator]
    return processed_offset_providers


def _process_metric_arguments(
    metric_level: Union[str, int],
    compute_time_argument: Union[str, Any],
    eval_mode: bool,
    backend: str,
    use_metrics: bool,
) -> Union[str, Any]:

    if not use_metrics:
        return tuple() if eval_mode else ""

    # This is currently different and should probably be unified somehow.
    if backend == "gtfn":
        raise NotImplementedError("Implement me")
    else:
        if eval_mode:
            assert not (isinstance(metric_level, str) or isinstance(compute_time_argument, str))
            return (metric_level, compute_time_argument)
        else:
            assert isinstance(metric_level, str) and isinstance(compute_time_argument, str)
            return f"{metric_level}, {compute_time_argument}, "


def _perform_argument_processing(
    args: tuple[Any, ...],
    offset_provider: Mapping[str, Any],
    metric_level: int,
    runtime_return_value: Any,
    use_metrics: bool,  # Not in generated signature, but must be provided.
    backend: str,  # Not part but must be provided.
) -> tuple[Any, ...]:

    # NOTE: Although the loop bellow looks like it could be turned into into a tuple
    #   comprehension it would lead to an error. This is related to the output type
    #   of `_process_argument()`. In essence it boils down to `append()` (comprehension)
    #   and `extend()` (loop).
    processed_arguments: tuple[Any, ...] = tuple()
    for arg in args:
        processed_arguments += _process_argument(  # type: ignore[call-overload]
            argument=arg, param_type=None, unpacked_variables=None, backend=backend
        )
    processed_arguments += _process_offset_providers(  # type: ignore[operator]
        offset_provider=offset_provider, eval_mode=True
    )
    processed_arguments += _process_metric_arguments(  # type: ignore[operator]
        metric_level=metric_level,
        compute_time_argument=runtime_return_value,
        eval_mode=True,
        backend=backend,
        use_metrics=use_metrics,
    )
    return processed_arguments
