# GT4Py - GridTools Framework
#
# Copyright (c) 2014-2024, ETH Zurich
# All rights reserved.
#
# Please, refer to the LICENSE file in the root directory.
# SPDX-License-Identifier: BSD-3-Clause

from __future__ import annotations

import dataclasses
from typing import Any, Container, Literal, Optional

import dace

from gt4py.next import common as gtx_common
from gt4py.next.iterator import ir
from gt4py.next.otf import code_specs, stages
from gt4py.next.program_processors.runners.dace import sdfg_args as gtx_sdfg_args
from gt4py.next.program_processors.runners.dace.workflow import common as gtx_wfdcommon
from gt4py.next.type_system import type_specifications as ts


def argument_processing_function(
    args: tuple[Any, ...],
    offset_provider: gtx_common.OffsetProvider,
    metrics_level: int,
    runtime_return_value: Any,
) -> Any:
    """Signature generated by `_create_sdfg_bindings()` and used to process the arguments for an SDFG call.

    See `_create_sdfg_bindings()` and `bind_sdfg()` for more.

    Args:
        args: The arguments that are passed to the SDFG. A tuple of fields and nested tuples.
        offset_provider: The offset providers (order is used verbatim).
        metrics_level: The level of the metric that is active.
        runtime_return_value: NumPy array used to write back the runtime spend in the call.
    """
    raise NotImplementedError("`argument_processing_function()` is only for documenting purposes.`")


def _create_sdfg_bindings(
    prog: ir.Program,
    offset_provider_type: gtx_common.OffsetProviderType,
    bind_func_name: str,
    use_metrics: bool,
    sdfg: Optional[dace.SDFG],
    backend: Literal["gtfn", "dace"],
) -> str:
    """
    Creates a Python function that translates GT4Py arguments into arguments suitable for a SDFG call.

    The returned string can be passed to exec to then dynamically create a function to
    perform the translation. The function will have the same signature as
    `argument_processing_function()` and have the name `bind_func_name`.
    The function that is generated targets the interface defined through the
    `user_args` defined interface of the SDFG.

    The function has experimental support for GTFN.

    Args:
        prog: The program definition.
        offset_provider_type: The offset provider types.
        bind_func_name: The name of the function to perform the translation.
        use_metrics: If metric support was added to the underlying compiled code.
            In that case the last two arguments of the generated function signature
            are ignored and also not included in the output.
        sdfg: If provided and `backend` is `dace` then only the offset providers that
            are used in the SDFG are processed, otherwise `None` is passed.
            This is compatible with the `user_args` signature.
        backend: For which backend the generated function should be used.
    """
    assert backend in ["gtfn", "dace"]

    code_lines: list[str] = []
    code_lines.append(f"def {bind_func_name}(")
    code_lines.append("\targs,")
    code_lines.append("\toffset_provider,")
    code_lines.append(f"\t{gtx_wfdcommon.SDFG_ARG_METRIC_LEVEL},")
    code_lines.append(f"\t{gtx_wfdcommon.SDFG_ARG_METRIC_COMPUTE_TIME},")
    code_lines.append("):")

    expanded_args = [f"__gtx_expanded_names_{param.id}" for param in prog.params]
    unpacked_variables = [", ".join(expanded_args) + ", = args"]
    process_arg_stmt = ""
    for arg_name, param in zip(expanded_args, prog.params):
        assert param.type is not None
        process_arg_stmt += _process_argument(
            argument=arg_name,
            param_type=param.type,
            unpacked_variables=unpacked_variables,
            backend=backend,
        )
        assert process_arg_stmt.strip().endswith(",")
    assert process_arg_stmt.strip().endswith(",")

    needed_offset_providers: Optional[Container[str]] = None
    if backend == "dace" and sdfg is not None:
        needed_offset_providers = {
            aname for aname in sdfg.arglist() if gtx_sdfg_args.is_connectivity_identifier(aname)
        }

    process_arg_stmt += _process_offset_providers(offset_provider_type, needed_offset_providers)

    process_arg_stmt += _process_metric_arguments(
        metric_level_arg_name=gtx_wfdcommon.SDFG_ARG_METRIC_LEVEL,
        compute_time_arg_name=gtx_wfdcommon.SDFG_ARG_METRIC_COMPUTE_TIME,
        backend=backend,
        use_metrics=use_metrics,
    )
    code_lines.extend(("\t" + s for s in unpacked_variables))
    code_lines.append(f"\treturn ({process_arg_stmt})")

    return "\n".join(code_lines)


def bind_sdfg(
    inp: stages.ProgramSource[code_specs.SDFGCodeSpec],
    bind_func_name: str,
) -> stages.ExtensionSource[code_specs.SDFGCodeSpec, code_specs.PythonCodeSpec]:
    """
    Method to be used as workflow stage for generation of SDFG bindings.

    Refer to `_create_sdfg_bindings()` documentation.
    """
    # NOTE: This function should actually call `_create_sdfg_bindings()` however,
    #   not all necessarily arguments are present here. For that reason they are
    #   generated by `DaCeTranslator.__call__()` and we just process them a little
    #   bit further.
    assert isinstance(inp.source_code, tuple) and len(inp.source_code) == 2

    source_code: tuple[str, dict] = inp.source_code
    binding_code_generated_during_translation, jsdfg = source_code
    assert f"def {bind_func_name}(" in binding_code_generated_during_translation

    program_source = dataclasses.replace(inp, source_code=jsdfg)
    binding_source = stages.BindingSource(
        binding_code_generated_during_translation, library_deps=tuple()
    )

    return stages.ExtensionSource(
        program_source=program_source,
        binding_source=binding_source,
    )


def _perfom_tuple_unpacking(
    tuple_argument: str,
    tuple_len: int,
    unpacked_variables: list[str],
) -> list[str]:
    assert tuple_len > 0
    unpacked_arguments = [f"{tuple_argument}_{i}" for i in range(tuple_len)]
    # Trailing comma is needed to handle 1 element tuples correctly.
    unpacked_variables.append(f"{', '.join(unpacked_arguments)}, = {tuple_argument}")
    return unpacked_arguments


def _process_argument(
    argument: str,
    param_type: ts.TypeSpec,
    unpacked_variables: list[str],
    backend: Literal["gtfn", "dace"],
) -> str:

    processed_argument = ""
    if isinstance(param_type, ts.TupleType):
        tuple_member_types = param_type.types
        tuple_members = _perfom_tuple_unpacking(
            argument, len(tuple_member_types), unpacked_variables
        )
        processed_argument = "("
        for tuple_member, tuple_member_type in zip(tuple_members, param_type.types):
            processed_argument += _process_argument(
                argument=tuple_member,
                param_type=tuple_member_type,
                unpacked_variables=unpacked_variables,
                backend=backend,
            )
        processed_argument += ")"

    elif isinstance(param_type, ts.FieldType):
        if len(param_type.dims) == 0:
            # GTFN wants a field, dace a scalar.
            processed_argument = argument if backend == "gtfn" else f"{argument}.as_scalar()"
        else:
            # Full array, the differences is where the origin comes from.
            origin_method = "__gt_origin__" if backend == "gtfn" else "__dace_origin__"
            processed_argument = f"({argument}.ndarray, ({argument}.{origin_method}))"

    elif isinstance(param_type, ts.ScalarType):
        processed_argument = (
            f"bool({argument})"
            if param_type.kind == ts.ScalarKind.BOOL and backend == "gtfn"
            else argument
        )
    else:
        raise ValueError(f"Parameter `{argument}` had unexpected type `{param_type}`")

    assert processed_argument
    return processed_argument + ", "


def _process_offset_providers(
    offset_provider_type: gtx_common.OffsetProviderType,
    needed_offset_providers: Optional[Container[str]],
) -> str:

    if needed_offset_providers is None:
        needed_offset_providers = set(offset_provider_type.keys())

    # Assumes that the order of the offset providers is stable.
    processed_offset_providers = ""
    for table_name in offset_provider_type:
        if table_name in needed_offset_providers:
            processed_offset_providers += f"(offset_provider['{table_name}'].ndarray, (0, 0))"
        else:
            processed_offset_providers += "None"
        processed_offset_providers += ", "

    return processed_offset_providers


def _process_metric_arguments(
    metric_level_arg_name: str,
    compute_time_arg_name: str,
    backend: Literal["gtfn", "dace"],
    use_metrics: bool,
) -> str:

    if not use_metrics:
        return ""

    # This is currently different and should probably be unified somehow.
    if backend == "gtfn":
        raise NotImplementedError()
    else:
        return f"{metric_level_arg_name}, {compute_time_arg_name}, "
