# GT4Py - GridTools Framework
#
# Copyright (c) 2014-2024, ETH Zurich
# All rights reserved.
#
# Please, refer to the LICENSE file in the root directory.
# SPDX-License-Identifier: BSD-3-Clause

from __future__ import annotations

from typing import Any, Literal, Optional, Sequence

import dace

from gt4py.next import common as gtx_common
from gt4py.next.otf import code_specs, stages
from gt4py.next.otf.binding import interface
from gt4py.next.program_processors.runners.dace import sdfg_args as gtx_sdfg_args
from gt4py.next.program_processors.runners.dace.workflow import common as gtx_wfdcommon
from gt4py.next.type_system import type_specifications as ts


def argument_processing_function(
    args: tuple[Any, ...],
    offset_provider: gtx_common.OffsetProvider,
    metrics_level: int,
    runtime_return_value: Any,
) -> tuple[tuple[Any, ...], dict[str, Any]]:
    """Signature generated by `_create_sdfg_bindings()` and used to process the arguments for an SDFG call.

    See `_create_sdfg_bindings()` and `bind_sdfg()` for more.

    Args:
        args: The arguments that are passed to the SDFG. A tuple of fields and nested tuples.
        offset_provider: The offset providers (order is used verbatim).
        metrics_level: The level of the metric that is active.
        runtime_return_value: NumPy array used to write back the runtime spend in the call.
    """
    raise NotImplementedError("`argument_processing_function()` is only for documenting purposes.`")


def _create_sdfg_bindings(
    program_parameters: Sequence[interface.Parameter],
    bind_func_name: str,
    use_metrics: bool,
    sdfg: Optional[dace.SDFG],
    backend: Literal["gtfn", "dace"],
) -> str:
    """
    Creates a Python function that translates GT4Py arguments into arguments suitable for a SDFG call.

    The returned string can be passed to exec to then dynamically create a function to
    perform the translation. The function will have the same signature as
    `argument_processing_function()` and have the name `bind_func_name`.
    The function that is generated targets the interface defined through the
    `user_args` defined interface of the SDFG.

    The function has experimental support for GTFN.

    Args:
        prog: The program definition.
        bind_func_name: The name of the function to perform the translation.
        use_metrics: If metric support was added to the underlying compiled code.
            In that case the last two arguments of the generated function signature
            are ignored and also not included in the output.
        sdfg: If provided and `backend` is `dace` then only the offset providers that
            are used in the SDFG are processed, otherwise `None` is passed.
            This is compatible with the `user_args` signature.
        backend: For which backend the generated function should be used.
    """
    assert backend in ["gtfn", "dace"]
    assert backend == "dace" or sdfg is None

    if backend == "dace":
        is_offset_arg_name = lambda arg_name: arg_name.startswith("@")  # noqa: E731 [lambda-assignment]
        get_offset_name_from_prog_arg_name = lambda arg_name: arg_name[1:]  # noqa: E731 [lambda-assignment]
        if sdfg is not None:
            sdfg_arglist = sdfg.arglist()
            is_offset_used = lambda offset_name: (  # noqa: E731 [lambda-assignment]
                gtx_sdfg_args.connectivity_identifier(offset_name) in sdfg_arglist
            )
        else:
            is_offset_used = lambda _: True  # noqa: E731 [lambda-assignment]
    else:
        raise NotImplementedError()

    code_lines: list[str] = []
    code_lines.append("_PAIR_OF_ZEROS = (0, 0)")
    code_lines.append(
        f"def {bind_func_name}(args, offset_provider, metrics_level, runtime_return_value):"
    )

    unpacked_program_arguments: list[Optional[str]] = [
        None if is_offset_arg_name(param.name) else f"__gtx_expanded_names_{param.name}"
        for param in program_parameters
    ]

    unpacked_variables = [
        ", ".join(arg for arg in unpacked_program_arguments if arg is not None) + ", = args"
    ]

    positional_arguments = ""
    kwargs_arguments: dict[str, str] = {}

    for arg_name, param in zip(unpacked_program_arguments, program_parameters, strict=True):
        assert param.type_ is not None
        real_arg_name = param.name

        if is_offset_arg_name(real_arg_name):
            assert arg_name is None
            offset_name = get_offset_name_from_prog_arg_name(real_arg_name)
            if is_offset_used(offset_name):
                positional_arguments += (
                    f"(offset_provider['{offset_name}'].ndarray, _PAIR_OF_ZEROS), "
                )
            else:
                positional_arguments += "None, "
        else:
            assert isinstance(arg_name, str)
            positional_arguments += _process_argument(
                argument=arg_name,
                param_type=param.type_,
                unpacked_variables=unpacked_variables,
                backend=backend,
            )
        assert positional_arguments.strip().endswith(",")
    assert positional_arguments.strip().endswith(",")

    positional_arguments, kwargs_arguments = _process_metric_arguments(
        metric_level_arg_name="metrics_level",
        compute_time_arg_name="runtime_return_value",
        positional_arguments=positional_arguments,
        kwargs_arguments=kwargs_arguments,
        backend=backend,
        use_metrics=use_metrics,
    )
    code_lines.extend(("\t" + s for s in unpacked_variables))
    code_lines.append(
        f"\treturn ({positional_arguments}), {{"
        + ", ".join(f"'{k}': {v}" for k, v in kwargs_arguments.items())
        + "}"
    )

    return "\n".join(code_lines)


def bind_sdfg(
    inp: stages.ProgramSource[code_specs.SDFGCodeSpec],
    bind_func_name: str,
) -> stages.ExtensionSource[code_specs.SDFGCodeSpec, code_specs.PythonCodeSpec]:
    """
    Method to be used as workflow stage for generation of SDFG bindings.

    Refer to `_create_sdfg_bindings()` documentation.
    """
    assert isinstance(inp.source_code, dict)

    sdfg = dace.SDFG.from_json(inp.source_code)
    use_metrics = gtx_wfdcommon.SDFG_ARG_METRIC_COMPUTE_TIME in sdfg.arrays

    bind_source = _create_sdfg_bindings(
        program_parameters=inp.entry_point.parameters,
        bind_func_name=bind_func_name,
        use_metrics=use_metrics,
        sdfg=sdfg,
        backend="dace",
    )
    binding_source = stages.BindingSource(bind_source, library_deps=tuple())

    return stages.ExtensionSource(
        program_source=inp,
        binding_source=binding_source,
    )


def _perfom_tuple_unpacking(
    tuple_argument: str,
    tuple_len: int,
    unpacked_variables: list[str],
) -> list[str]:
    assert tuple_len > 0
    unpacked_arguments = [f"{tuple_argument}_{i}" for i in range(tuple_len)]
    # Trailing comma is needed to handle 1 element tuples correctly.
    unpacked_variables.append(f"{', '.join(unpacked_arguments)}, = {tuple_argument}")
    return unpacked_arguments


def _process_argument(
    argument: str,
    param_type: ts.TypeSpec,
    unpacked_variables: list[str],
    backend: Literal["gtfn", "dace"],
) -> str:
    processed_argument = ""
    if isinstance(param_type, ts.TupleType):
        tuple_member_types = param_type.types
        tuple_members = _perfom_tuple_unpacking(
            argument, len(tuple_member_types), unpacked_variables
        )
        processed_argument = "("
        for tuple_member, tuple_member_type in zip(tuple_members, param_type.types):
            processed_argument += _process_argument(
                argument=tuple_member,
                param_type=tuple_member_type,
                unpacked_variables=unpacked_variables,
                backend=backend,
            )
        processed_argument += ")"

    elif isinstance(param_type, ts.FieldType):
        if len(param_type.dims) == 0:
            # GTFN wants a field, dace a scalar.
            processed_argument = argument if backend == "gtfn" else f"{argument}.as_scalar()"
        else:
            # Full array, the differences is where the origin comes from.
            origin_method = "__gt_origin__" if backend == "gtfn" else "__dace_origin__"
            processed_argument = f"({argument}.ndarray, ({argument}.{origin_method}))"

    elif isinstance(param_type, ts.ScalarType):
        processed_argument = (
            f"bool({argument})"
            if param_type.kind == ts.ScalarKind.BOOL and backend == "gtfn"
            else argument
        )
    else:
        raise ValueError(f"Parameter `{argument}` had unexpected type `{param_type}`")

    assert processed_argument
    return processed_argument + ", "


def _process_metric_arguments(
    metric_level_arg_name: str,
    compute_time_arg_name: str,
    positional_arguments: str,
    kwargs_arguments: dict[str, str],
    backend: Literal["gtfn", "dace"],
    use_metrics: bool,
) -> tuple[str, dict[str, str]]:

    if use_metrics:
        if backend == "gtfn":
            raise NotImplementedError()
        else:
            assert positional_arguments.strip().endswith(",")
            positional_arguments += f"{metric_level_arg_name}, {compute_time_arg_name}, "

    return positional_arguments, kwargs_arguments
