# GT4Py - GridTools Framework
#
# Copyright (c) 2014-2024, ETH Zurich
# All rights reserved.
#
# Please, refer to the LICENSE file in the root directory.
# SPDX-License-Identifier: BSD-3-Clause

import copy
from typing import Any, Optional

import dace
from dace import (
    data as dace_data,
    properties as dace_properties,
    subsets as dace_sbs,
    transformation as dace_transformation,
)
from dace.sdfg import graph as dace_graph, nodes as dace_nodes
from dace.transformation.passes import analysis as dace_analysis

from gt4py.next import config as gtx_config
from gt4py.next.program_processors.runners.dace import (
    library_nodes as gtx_lib_nodes,
    transformations as gtx_transformations,
)


@dace_properties.make_properties
class InlineBroadcastAccess(dace_transformation.SingleStateTransformation):
    """Inline Broadcast nodes.

    The transformation performs two kinds of operations that are related to
    broadcast library nodes. However, this transformation only operates on
    broadcast of scalar values.

    The first one is "static access replacement" in that the operation pattern:
    ```
        (value_to_broadcast) --> [BroadCast] --> (bcast_result) --> MapEnty
    ```
    is matched and transformed into:
    ```
        (value_to_broadcase) --> MapEntry
    ```
    Thus instead of filling an array with a value and then reading from that
    big filled array, the Map directly reads from the value that should be
    broadcasted. The only restriction is, that the accesses are known at
    compile time, i.e. no neighbourhood accesses are supported.

    The second kind of operation is "AccessNode bypassing" in which the
    following pattern is matched:
    ```
        (value_to_broadcast) --> [Broadcast] --> (bcast_result) --> (access_node_consumer)
    ```
    to:
    ```
        (value_to_broadcast) --> [Broadcast] --> (access_node_consumer)
    ```
    Thus, the broadcast is performed directly into the target destination.

    It is important that these two modes can be performed at the same time.
    Meaning `bcast_result` can have multiple consumers.

    Args:
        clean_dead_dataflow: Perform dead dataflow elimination.
        single_use_data: Use this as single use data, if not given
            `FindSingleUseData` will be run at every `apply()` call.

    Note:
        In the "AccessNode bypassing" mode each (AccessNode) consumer will
        have its own broadcast, but all will read from the same value to
        broadcast.

    Todo:
        - Rename this transformation, as it now supports scalars.
    """

    bcast_value = dace_transformation.PatternNode(dace_nodes.AccessNode)
    bcast_node = dace_transformation.PatternNode(gtx_lib_nodes.Broadcast)
    bcast_result = dace_transformation.PatternNode(dace_nodes.AccessNode)

    clean_dead_dataflow = dace_properties.Property(
        dtype=bool,
        allow_none=False,
        default=True,
        desc="Clean dead dataflow.",
    )

    # Name of all data that is used at only one place. Is computed by the
    #  `FindSingleUseData` pass and be passed at construction time. Needed until
    #  [issue#1911](https://github.com/spcl/dace/issues/1911) has been solved.
    _single_use_data: Optional[dict[dace.SDFG, set[str]]]

    @classmethod
    def expressions(cls) -> Any:
        return [
            dace.sdfg.utils.node_path_graph(
                cls.bcast_value,
                cls.bcast_node,
                cls.bcast_result,
            )
        ]

    def __init__(
        self,
        *args: Any,
        clean_dead_dataflow: Optional[bool] = None,
        single_use_data: Optional[dict[dace.SDFG, set[str]]] = None,
        **kwargs: Any,
    ) -> None:
        self._single_use_data = single_use_data
        if clean_dead_dataflow is not None:
            self.clean_dead_dataflow = clean_dead_dataflow

        super().__init__(*args, **kwargs)

    def can_be_applied(
        self,
        graph: dace.SDFGState,
        expr_index: int,
        sdfg: dace.SDFG,
        permissive: bool = False,
    ) -> bool:
        bcast_value = self.bcast_value
        bcast_node = self.bcast_node
        bcast_result = self.bcast_result
        bcast_result_desc = bcast_result.desc(sdfg)
        bcast_value_desc = bcast_value.desc(sdfg)
        assert graph.in_degree(self.bcast_node) == 1
        assert graph.out_degree(self.bcast_node) == 1

        # A fundamental requirement is that `bcast_result` is only generated by us.
        #  ADR-18 guarantees us this if it is transient and has a single producer,
        #  `bcast_node`. However, since we will remove `bcast_result`, we have to
        #  make sure that it is not used anywhere else.
        if graph.in_degree(bcast_result) != 1:
            return False
        if not bcast_result_desc.transient:
            return False
        if bcast_value_desc.dtype != bcast_result_desc.dtype:
            return False

        # Check single single use if a cached result is known, otherwise do it at the end.
        if self._single_use_data is not None:
            if bcast_result.data not in self._single_use_data[sdfg]:
                return False

        # We do not allow view!
        if gtx_transformations.utils.is_view(bcast_result_desc):
            return False
        if gtx_transformations.utils.is_view(bcast_value_desc):
            return False

        # NOTE: The big question is if it favourable to perform the transformation
        #   every time. If there are only AccessNodes consumers then the answer is
        #   probably yes, as we can remove the read and write of the initial data
        #   only the write to final destination is left. If the consumers are Maps
        #   the thing is a bit different. As we have to create the intermediate
        #   allocation. If the read of the memory is okay the `InlineBroadcastAccess`
        #   transformation can get rid of it. However, if this is not possible then
        #   you would need to allocate more memory than before. Thus, we require
        #   that the Maps consumers can be handled by `InlineBroadcastAccess`.

        # Now we have to inspect all consumers of the result node.
        for consumer_edge in graph.out_edges(bcast_result):
            if consumer_edge.data.is_empty():
                return False

            match consumer := consumer_edge.dst:
                case dace_nodes.AccessNode():
                    if gtx_transformations.utils.is_view(consumer, sdfg):
                        return False

                    # Otherwise we would end up with not enough named parameters
                    #  during expansion.
                    # TODO(phimuell): Since a Memlet is essentially a copy this case
                    #   can be handled by adding dummy dimensions, but we would need
                    #   to run some more analysis.
                    if bcast_node.params is not None and (
                        len(consumer.desc(sdfg).shape) != len(bcast_result_desc.shape)
                    ):
                        return False

                case dace_nodes.MapEntry():
                    if not self._check_map_consumer(
                        state=graph,
                        sdfg=sdfg,
                        bcast_value=bcast_value,
                        supplier_edge=consumer_edge,
                    ):
                        return False

                case dace_nodes.NestedSDFG():
                    # TODO(phimuell): Consider implementing this case.
                    return False

                case _:
                    # This kind of node can not be handled.
                    return False

        # Check single use data if it was not known at the beginning.
        if self._single_use_data is None:
            find_single_use_data = dace_analysis.FindSingleUseData()
            single_use_data = find_single_use_data.apply_pass(sdfg, None)
            if bcast_result.data not in single_use_data[sdfg]:
                return False

        return True

    def apply(
        self,
        graph: dace.SDFGState,
        sdfg: dace.SDFG,
    ) -> None:
        # Since the information what should be written is fully encoded in the
        #  destination subset of the `(bcast_result) -> (access_node)` edge
        #  we can now copy the edge.
        bcast_value = self.bcast_value
        bcast_node = self.bcast_node
        bcast_result = self.bcast_result

        for consumer_edge in graph.out_edges(bcast_result):
            match consumer := consumer_edge.dst:
                case dace_nodes.AccessNode():
                    self._handle_access_node_consumer(
                        state=graph,
                        bcast_value=bcast_value,
                        bcast_node=bcast_node,
                        bcast_result=bcast_result,
                        consumer_edge=consumer_edge,
                    )

                case dace_nodes.MapEntry():
                    self._handle_map_consumer(
                        state=graph,
                        sdfg=sdfg,
                        bcast_value=bcast_value,
                        bcast_node=bcast_node,
                        bcast_result=bcast_result,
                        consumer_edge=consumer_edge,
                    )

                case _:
                    raise NotImplementedError(
                        f"Node type `{type(consumer).__name__}` is not supported."
                    )

        # Check if we can remove the `bcast_result` node.
        if self.clean_dead_dataflow and graph.out_degree(bcast_result) == 0:
            # We have to figuring out
            if self._single_use_data is None:
                find_single_use_data = dace_analysis.FindSingleUseData()
                single_use_data = find_single_use_data.apply_pass(sdfg, None)
            else:
                single_use_data = self._single_use_data

            if bcast_result.data in single_use_data[sdfg]:
                graph.remove_node(bcast_result)
                graph.remove_node(bcast_node)
                sdfg.remove_data(bcast_result.data, validate=__debug__)

    @staticmethod
    def _handle_access_node_consumer(
        state: dace.SDFGState,
        bcast_value: dace_nodes.AccessNode,
        bcast_node: gtx_lib_nodes.Broadcast,
        bcast_result: dace_nodes.AccessNode,
        consumer_edge: dace_graph.MultiConnectorEdge[dace.Memlet],
    ) -> dace_graph.MultiConnectorEdge[dace.Memlet]:
        """Bypass `bcast_result` and perform the broadcast directly into `consumer_edge.dst`.

        The function will replicate the broadcast node but it will be connected to
        `bcast_value`. Furthermore, the function will remove `consumer_edge`.

        In case there are multiple edges between `bcast_result` and the destination
        of `consumer_edge` the function is called multiple times, once for each
        connection.
        """

        # Create a new node and find a new name for it.
        new_bcast_node = copy.deepcopy(bcast_node)
        known_bcast_names: set[str] = set()
        for other_state in state.sdfg.states():
            for node in other_state.nodes():
                if isinstance(node, gtx_lib_nodes.Broadcast):
                    known_bcast_names.add(node.label)
        new_bcast_name = dace.utils.find_new_name(new_bcast_node.label, known_bcast_names)
        new_bcast_node.name = new_bcast_name
        new_bcast_node.label = new_bcast_name

        # TODO(phimuell): Handle empty edges.
        assert state.in_degree(bcast_node) == 1
        bcast_value_edge = next(iter(state.in_edges(bcast_node)))
        assert bcast_value_edge.src is bcast_value

        # Add the new broadcast node and connect it to `bcast_value`.
        state.add_node(new_bcast_node)
        state.add_edge(
            bcast_value,
            None,
            new_bcast_node,
            "_inp",
            copy.deepcopy(bcast_value_edge.data),
        )

        new_dst_subset: dace_sbs.Subset = copy.deepcopy(
            consumer_edge.data.get_dst_subset(consumer_edge, state)
        )
        assert new_dst_subset is not None
        new_consumer_edge = state.add_edge(
            new_bcast_node,
            "_outp",
            consumer_edge.dst,
            consumer_edge.dst_conn,
            dace.Memlet(data=consumer_edge.dst.data, subset=new_dst_subset),
        )
        state.remove_edge(consumer_edge)

        return new_consumer_edge

    @staticmethod
    def _check_map_consumer(
        state: dace.SDFGState,
        sdfg: dace.SDFG,
        bcast_value: dace_nodes.AccessNode,
        supplier_edge: dace_graph.MultiConnectorEdge[dace.Memlet],
    ) -> bool:
        """Check if the transformation can handle the Map.

        The function expects that `supplier_edge` connects the `bcast_result` to
        a Map that consumes it.
        The function essentially checks if all accesses are known at compile time
        and that they only perform a single access.
        """
        assert isinstance(supplier_edge.src, dace_nodes.AccessNode)
        assert isinstance(supplier_edge.dst, dace_nodes.MapEntry)

        if supplier_edge.data.is_empty():
            return False
        if not supplier_edge.dst_conn.startswith("IN_"):
            return False

        bcast_result: dace_nodes.AccessNode = supplier_edge.src
        bcast_value_desc = sdfg.arrays[bcast_value.data]
        map_entry: dace_nodes.MapEntry = supplier_edge.dst
        inner_connector = "OUT_" + supplier_edge.dst_conn[3:]
        scope_dict = state.scope_dict()

        for consumer_edge in state.out_edges_by_connector(map_entry, inner_connector):
            for final_consumer in state.memlet_tree(consumer_edge).leaves():
                sbs_to_inspect = (
                    final_consumer.data.subset
                    if final_consumer.data.data == bcast_result.data
                    else final_consumer.data.other_subset
                )
                assert sbs_to_inspect is not None

                # Currently the only test we do is, that only one element from
                #  `bcast_result` is loaded. However, the location of this
                #  element needs to be known. This rejects neighbourhood accesses.
                if (sbs_to_inspect.num_elements() == 1) == False:  # noqa: E712 [true-false-comparison]  # SymPy comparison
                    return False

                if isinstance(bcast_value_desc, dace_data.Scalar):
                    # If `bcast_value` is a scalar then we do not impose any further
                    #  restrictions.
                    pass

                else:
                    # In case `bcast_value` is not a scalar, then we require that the
                    #  consumer is not nested. This is a simplification to avoids
                    #  updating the Memlet trees.
                    # TODO(phimuell): Lift this requirement.
                    if scope_dict[final_consumer.dst] is not map_entry:
                        return False

        return True

    @staticmethod
    def _handle_map_consumer(
        state: dace.SDFGState,
        sdfg: dace.SDFG,
        bcast_node: gtx_lib_nodes.Broadcast,
        bcast_value: dace_nodes.AccessNode,
        bcast_result: dace_nodes.AccessNode,
        consumer_edge: dace_graph.MultiConnectorEdge[dace.Memlet],
    ) -> None:
        """Replace accesses to `bcast_result`, performed through `consumer_edge` by accesses to `bcast_value`.

        The function expects that `consumer_edge` ends at a MapEntry node.

        Note:
            - The function will ignore all outgoing edges of `bcast_result` that are
                not going to `map_entry`.
            - If there are multiple connections between `bcast_result` and the
                destination of `consumer_edge` then this function is called multiple
                times, once for each connection.
        """

        map_entry = consumer_edge.dst
        scope_dict = state.scope_dict()
        assert isinstance(map_entry, dace_nodes.MapEntry)
        assert consumer_edge.dst_conn.startswith("IN_")
        assert consumer_edge.src is bcast_result

        # Make `bcast_value` available inside the Map body.
        bcast_value_conn: str | None = None
        bcast_value_desc = sdfg.arrays[bcast_value.data]
        for edge in state.out_edges(bcast_value):
            if edge.dst is not map_entry:
                continue
            if edge.data.is_empty():
                continue
            if not edge.dst_conn.startswith("IN_"):
                continue
            bcast_value_conn = "OUT_" + edge.dst_conn[3:]
            edge.data.subset = dace_sbs.Range.from_array(bcast_value_desc)
            break

        else:
            # There was no connection between them so we have to create one.
            bcast_value_conn_raw = map_entry.next_connector(bcast_value.data)
            state.add_edge(
                bcast_value,
                None,
                map_entry,
                "IN_" + bcast_value_conn_raw,
                sdfg.make_array_memlet(bcast_value.data),
            )
            bcast_value_conn = "OUT_" + bcast_value_conn_raw
            map_entry.add_scope_connectors(bcast_value_conn_raw, force=True)
        assert bcast_value_conn in map_entry.out_connectors

        is_vector_broadcast = not isinstance(bcast_value_desc, dace_data.Scalar)
        inner_connector = "OUT_" + consumer_edge.dst_conn[3:]
        bcast_value_offset = next(iter(state.in_edges(bcast_node))).data.subset.min_element()
        bcast_result_offset = next(iter(state.out_edges(bcast_node))).data.subset.min_element()

        # Note regardless if we have a scalar or a vector broadcast, since we have
        #  ensured that everything is a scalar read, we only need to modify the
        #  respective subset, there is not need for fancy updates.
        for inner_map_edge in list(state.out_edges_by_connector(map_entry, inner_connector)):
            new_consumer_sbs: list[str] = []
            for mtree in state.memlet_tree(inner_map_edge).traverse_children(True):
                tree_edge = mtree.edge
                assert tree_edge.data.wcr is None

                if is_vector_broadcast:
                    # In vector broadcast we limit ourselves to "direct read", i.e. no
                    #  nesting, we do this because of the new map parameters that are
                    #  potentially introduced. Furthermore, updating the Memlet tress
                    #  would also be a bit difficult.
                    #  Thus, this body is only called once per `inner_map_edge`.
                    assert scope_dict[tree_edge.dst] is map_entry
                    assert tree_edge.src is map_entry
                    assert inner_map_edge is tree_edge
                    broadcast_in_dims: list[int] = bcast_node.brodcast_in_dims
                    consumer_sbs: dace_sbs.Subset = (
                        tree_edge.data.subset
                        if tree_edge.data.data == bcast_result.data
                        else tree_edge.data.other_subset
                    )

                    for bcast_res_dim, (sbs_acc, _, _) in enumerate(consumer_sbs):
                        if bcast_res_dim not in broadcast_in_dims:
                            # This is a replicated dimension, we can ignore it.
                            continue
                        else:
                            bcast_val_dim = broadcast_in_dims.index(bcast_res_dim)
                            new_consumer_sbs.append(
                                f"({sbs_acc}) - ({bcast_result_offset[bcast_res_dim]}) + ({bcast_value_offset[bcast_val_dim]})"
                            )
                    assert len(new_consumer_sbs) == len(bcast_value_offset)

                else:
                    # In the scalar case we allow for very deep nested Memlet tress.
                    #  However, since the subset is always `0` the updates are also
                    #  very simple.
                    new_consumer_sbs.append("0")

                if tree_edge.data.data == bcast_result.data:
                    tree_edge.data.data = bcast_value.data
                    tree_edge.data.subset = dace_sbs.Range.from_string(", ".join(new_consumer_sbs))
                else:
                    tree_edge.data.other_subset = dace_sbs.Range.from_string(
                        ", ".join(new_consumer_sbs)
                    )

            # Now reroute `inner_map_edge` such that it reads from `bcast_value`
            #  directly, which is available from `bcast_value_conn` at `map_entry`.
            state.add_edge(
                map_entry,
                bcast_value_conn,
                inner_map_edge.dst,
                inner_map_edge.dst_conn,
                inner_map_edge.data,  # Was modified above.
            )
            state.remove_edge(inner_map_edge)
            map_entry.remove_out_connector(inner_map_edge.src_conn)

        # Now remove the connection `(bcast_result) -> map_entry`.
        map_entry.remove_in_connector(consumer_edge.dst_conn)
        state.remove_edge(consumer_edge)


@dace_properties.make_properties
class BrodcastChainRemover(dace_transformation.SingleStateTransformation):
    """
    Removes a chain of broadcasts operation.

    It matches the pattern:
    ```
        (bcast_value) -----> [Broadcast1] ----> (bcast_tmp) ----> [Broadcast2]
    ```
    and turns it into:
    ```
        (bcast_value) ----> [Broadcast2]
    ```

    `bcast_tmp` can have multiple consumers. If after the rerouting `bcast_tmp` is
    no longer used it is removed.

    There is currently an implementation limitation, in that `brodcast_in_dims` of
    the first broadcast node must be an empty list. Which is roughly equivalent to
    say that `bcast_value` is a scalar.

    Args:
        single_use_data: Use this as single use data, if not given
            `FindSingleUseData` will be run at every `apply()` call.

    Todo:
        Lift the limitation on `BroadcastNode1::brodcast_in_dims`.

    Note:
        This transformation processes more than was matched.
    """

    bcast_value = dace_transformation.PatternNode(dace_nodes.AccessNode)
    bcast_node1 = dace_transformation.PatternNode(gtx_lib_nodes.Broadcast)
    bcast_tmp = dace_transformation.PatternNode(dace_nodes.AccessNode)
    bcast_node2 = dace_transformation.PatternNode(
        gtx_lib_nodes.Broadcast
    )  # Only for speed up matching.

    # Name of all data that is used at only one place. Is computed by the
    #  `FindSingleUseData` pass and be passed at construction time. Needed until
    #  [issue#1911](https://github.com/spcl/dace/issues/1911) has been solved.
    _single_use_data: Optional[dict[dace.SDFG, set[str]]]

    @classmethod
    def expressions(cls) -> Any:
        return [
            dace.sdfg.utils.node_path_graph(
                cls.bcast_value,
                cls.bcast_node1,
                cls.bcast_tmp,
                cls.bcast_node2,
            )
        ]

    def __init__(
        self,
        *args: Any,
        single_use_data: Optional[dict[dace.SDFG, set[str]]] = None,
        **kwargs: Any,
    ) -> None:
        self._single_use_data = single_use_data
        super().__init__(*args, **kwargs)

    def can_be_applied(
        self,
        graph: dace.SDFGState,
        expr_index: int,
        sdfg: dace.SDFG,
        permissive: bool = False,
    ) -> bool:
        bcast_node1 = self.bcast_node1
        bcast_tmp = self.bcast_tmp

        # `bcast_tmp` must be fully generated by the first broadcast node. We do not
        #  need to check here if it is single use data. This will be done in `apply()`.
        if graph.in_degree(bcast_tmp) != 1:
            return False

        # This is a pure simplification.
        # TODO(phimuell): Implement this case.
        if len(bcast_node1.brodcast_in_dims) != 0:
            return False

        # All consumers of `bcast_tmp` must be broadcast nodes as well.
        found_other_bcast_node = False
        for oedge in graph.out_edges(bcast_tmp):
            if isinstance(oedge.dst, gtx_lib_nodes.Broadcast):
                found_other_bcast_node = True

        # We must found some other broadcast nodes.
        if not found_other_bcast_node:
            return False

        return True

    def apply(
        self,
        graph: dace.SDFGState,
        sdfg: dace.SDFG,
    ) -> None:
        bcast_node1: gtx_lib_nodes.Broadcast = self.bcast_node1
        bcast_tmp: dace_nodes.AccessNode = self.bcast_tmp

        bcast_value = self.bcast_value
        bcast_value_edge = next(iter(graph.in_edges(bcast_node1)))

        # This is possible because we have checked the `brodcast_in_dims`.
        assert len(bcast_node1.brodcast_in_dims) == 0

        # Go through all consumer and bypass the first broadcast node.
        for oedge in list(graph.out_edges(bcast_tmp)):
            consumer = oedge.dst
            if not isinstance(consumer, gtx_lib_nodes.Broadcast):
                continue

            consumer.brodcast_in_dims = []  # Possible because of simplification.
            graph.add_edge(
                bcast_value,
                None,
                consumer,
                "_inp",
                copy.deepcopy(bcast_value_edge.data),
            )
            graph.remove_edge(oedge)

        # If `bcast_tmp` still has consumer then we are done, because we can not
        #  delete it.
        if graph.out_degree(bcast_value) > 0:
            return

        # If there are no consumer, we must check if it is single use data, i.e. used
        #  in another state.
        if self._single_use_data is None:
            find_single_use_data = dace_analysis.FindSingleUseData()
            single_use_data = find_single_use_data.apply_pass(sdfg, None)
        else:
            single_use_data = self._single_use_data

        if bcast_tmp.data in single_use_data[sdfg]:
            # It is single use data and so we can delete it.
            graph.remove_node(bcast_tmp)
            graph.remove_node(bcast_node1)
            sdfg.remove_data(bcast_tmp.data, validate=gtx_config.DEBUG)
