include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

.py310: &py310
  PYVERSION_PREFIX: py310
  PYVERSION: 3.10.9
  IMAGE_NAME: gt4py

.py39: &py39
  PYVERSION_PREFIX: py39
  PYVERSION: 3.9.1
  IMAGE_NAME: gt4py

.py38: &py38
  PYVERSION_PREFIX: py38
  PYVERSION: 3.8.5
  IMAGE_NAME: gt4py

stages:
- image
- test

build py38:
  extends: .container-builder
  stage: image
  variables:
    PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/$IMAGE_NAME/gt4py-ci:$PYVERSION
    <<: *py38
    DOCKERFILE: Dockerfile
    DOCKER_BUILD_ARGS: '["PYVERSION=$PYVERSION", "CI_PROJECT_DIR=$CI_PROJECT_DIR"]'

build py39:
  extends: build py38
  variables:
    <<: *py39

build py310:
  extends: build py38
  variables:
    <<: *py310

test py38:
  extends: .daint
  needs: ["build py38"]
  stage: test
  image: $CSCS_REGISTRY_PATH/$IMAGE_NAME/gt4py-ci:$PYVERSION
  script:
  - python -c "import cupy"
  - pip install clang-format
  - tox --sitepackages -r -e $PYVERSION_PREFIX-all-cuda112
  variables:
    CRAY_CUDA_MPS: 1
    PULL_IMAGE: "YES"
    SLURM_CONSTRAINT: gpu
    SLURM_JOB_NUM_NODES: 1
    SLURM_TIMELIMIT: 120
    NUM_PROCESSES: 12
    <<: *py38

test py39:
  extends: test py38
  needs: ["build py39"]
  variables:
    <<: *py39

test py310:
  extends: test py38
  needs: ["build py310"]
  variables:
    <<: *py310
