include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.cscs.yml'

stages:
  - image
  - test
  - cleanup

variables:
  PY38: 3.8.5
  PY37: 3.7.9
  PY36: 3.6.12

build py38:
  extends: .dind
  stage: image
  variables:
    BUILD_IMAGE: $CI_REGISTRY_IMAGE/gt4py-ci/image:$PYVERSION
    PYVERSION: $PY38
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $BUILD_IMAGE || echo "has not been built yet"
    - docker build --network=host --cache-from $BUILD_IMAGE --build-arg BUILDKIT_INLINE_CACHE=1 --build-arg PYVERSION=$PYVERSION --build-arg CI_PROJECT_DIR=$CI_PROJECT_DIR -t $BUILD_IMAGE .
    - docker push $BUILD_IMAGE
  only:
    - master
    - staging
    - trying

build py37:
  extends: build py38
  variables:
    PYVERSION: $PY37

build py36:
  extends: build py38
  variables:
    PYVERSION: $PY36

test py38:
  extends: .daint
  only:
    - master
    - staging
    - trying
  needs: ["build py38"]
  stage: test
  image: $CI_REGISTRY_IMAGE/gt4py-ci/image:$PYVERSION
  script: 
    - python -c "import cupy"
    - tox --sitepackages -r -e $PYVERSION_PREFIX-cuda101
  variables:
    CRAY_CUDA_MPS: 1
    PULL_IMAGE: "YES"
    SLURM_CONSTRAINT: gpu
    SLURM_JOB_NUM_NODES: 1
    SLURM_TIMELIMIT: 120
    PYVERSION_PREFIX: py38
    PYVERSION: $PY38

test py37:
  extends: test py38
  needs: ["build py37"]
  variables:
    PYVERSION_PREFIX: py37
    PYVERSION: $PY37

test py36:
  extends: test py38
  needs: ["build py36"]
  variables:
    PYVERSION_PREFIX: py36
    PYVERSION: $PY36

notify_github_success:
  stage: cleanup
  when: on_success
  only: ["master", "staging", "trying"]
  tags: ["kubernetes"]
  image: stabbles/git-curl
  script: ./ci/set_github_status.sh success

notify_github_failure:
  stage: cleanup
  when: on_failure
  only: ["master", "staging", "trying"]
  tags: ["kubernetes"]
  image: stabbles/git-curl
  script: ./ci/set_github_status.sh failure
