codecov:
  require_ci_to_pass: no

flag_management:
  default_rules:
    carryforward: true
    statuses:
    - type: project
      target: auto
      threshold: 0%
    - type: patch
      target: 85%
  individual_flags:
  - name: gt4py-all
    paths:
    - src/functional
    carryforward: true
    statuses:
    - type: project
      target: 20%
    - type: patch
      target: 85%
  - name: eve-all
    paths:
    - src/eve
    carryforward: true
    statuses:
    - type: project
      target: 20%
    - type: patch
      target: 85%

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
