codecov:
  require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "85...100"
  status:
    project:
      default: false
      gt4py:
        target: 85%
        threshold: 100%
        paths:
        - "src/functional"
        if_ci_failed: success
      eve:
        target: 85%
        threshold: 100%
        paths:
        - "src/eve"
        if_ci_failed: success

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
