# This file is used by some of the development scripts (at '/scripts')
# to configure which Nox test sessions should be run based on the changed
# files from a base commit.
sessions:
  - name: test_cartesian
    ignore-paths: # Skip when only gt4py.next or doc files have been updated
      - "src/gt4py/next/**"
      - "tests/next_tests/**"
      - "examples/**"
      - "*.md"
      - "*.rst"

  - name: test_eve
    paths: # Run when gt4py.eve files (or package settings) are changed
      - "src/gt4py/eve/**"
      - "tests/eve_tests/**"
      - ".github/workflows/**"
      - "ci/**"
      - "*.lock"
      - "*.toml"
      - "*.yml"
      - "noxfile.py"

  - name: test_next
    ignore-paths: # Skip when only gt4py.cartesian or doc files have been updated
      - "src/gt4py/cartesian/**"
      - "tests/cartesian_tests/**"
      - "examples/**"
      - "*.md"
      - "*.rst"

  - name: test_storage
    paths: # Run when gt4py.storage files (or package settings) are changed
      - "src/gt4py/storage/**"
      - "src/gt4py/cartesian/backend/**" # For DaCe storages
      - "tests/storage_tests/**"
      - ".github/workflows/**"
      - "ci/**"
      - "*.lock"
      - "*.toml"
      - "*.yml"
      - "noxfile.py"

