name: Documentation

on:
  push:
    branches:
    - functional
  pull_request:
    branches:
    - functional

jobs:
  quickstart-guide:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
    - name: Run quickstart guide notebook
      run: |-
        pyversion=${{ matrix.python-version }}
        pyversion_no_dot=${pyversion//./}
        pip install tox
        tox -r -e docs
