stages:
  - cscs_ci

build images:
  stage: cscs_ci

  parallel:
    matrix:
      - PYVERSION_PREFIX: py310
        PYVERSION: 3.10.9
      - PYVERSION_PREFIX: py39
        PYVERSION: 3.9.1
      - PYVERSION_PREFIX: py38
        PYVERSION: 3.8.5

  trigger:
    include:
      - local: images.yml

run tests:
  stage: cscs_ci
  needs: ["build image"]
  parallel:
    matrix:
      - PYVERSION_PREFIX: py310
        PYVERSION: 3.10.9
      - PYVERSION_PREFIX: py39
        PYVERSION: 3.9.1
      - PYVERSION_PREFIX: py38
        PYVERSION: 3.8.5

  trigger:
    include:
      - local: cartesian.yml
      - local: storage.yml



