include:
- remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - build
  - test

build images:
  stage: cscs_ci

  parallel:
    matrix:
      - PYVERSION_PREFIX: py310
        PYVERSION: 3.10.9
      - PYVERSION_PREFIX: py39
        PYVERSION: 3.9.1
      - PYVERSION_PREFIX: py38
        PYVERSION: 3.8.5

  trigger:
    include:
      - local: ci/images.yml

run tests:
  stage: cscs_ci
  needs: ["build image"]
  parallel:
    matrix:
      - PYVERSION_PREFIX: py310
        PYVERSION: 3.10.9
      - PYVERSION_PREFIX: py39
        PYVERSION: 3.9.1
      - PYVERSION_PREFIX: py38
        PYVERSION: 3.8.5

  trigger:
    include:
      - local: ci/cartesian.yml
      - local: ci/storage.yml



