include:
- remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - baseimage
  - image

build base image:
  extends: .container-builder
  stage: baseimage
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
      when: manual
  allow_failure: true
  variables:
    PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/base/gt4py-ci:$PYVERSION
    DOCKERFILE: ci/base.Dockerfile
    DOCKER_BUILD_ARGS: '["PYVERSION=$PYVERSION", "CI_PROJECT_DIR=$CI_PROJECT_DIR"]'

build checkout image:
  extends: .container-builder
  stage: image
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
  variables:
    PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/gt4py/gt4py-ci:$PYVERSION
    DOCKERFILE: ci/checkout.Dockerfile
    DOCKER_BUILD_ARGS: '["PYVERSION=$PYVERSION", "CSCS_REGISTRY_PATH=$CSCS_REGISTRY_PATH"]'
