import typing
from typing import Any
import numpy

class BlockConnectivity:
    def __eq__(self, value, /) -> Any: ...
    def __ge__(self, value, /) -> Any: ...
    def __getitem__(*args: Any, **kwargs: Any) -> Any: ...
    def __gt__(self, value, /) -> Any: ...
    def __hash__(self, /) -> Any: ...
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def __le__(self, value, /) -> Any: ...
    def __lt__(self, value, /) -> Any: ...
    def __ne__(self, value, /) -> Any: ...
    def __repr__(self, /) -> Any: ...
    def __str__(self, /) -> Any: ...
    cols: Any = ...
    rows: Any = ...

class Config:
    def __eq__(self, value, /) -> Any: ...
    def __ge__(self, value, /) -> Any: ...
    def __getitem__(*args: Any, **kwargs: Any) -> Any: ...
    def __gt__(self, value, /) -> Any: ...
    def __hash__(self, /) -> Any: ...
    def __init__(*args: Any, **kwargs: Any) -> Any: ...
    def __le__(self, value, /) -> Any: ...
    def __lt__(self, value, /) -> Any: ...
    def __ne__(self, value, /) -> Any: ...
    def __repr__(*args: Any, **kwargs: Any) -> Any: ...
    def __setitem__(*args: Any, **kwargs: Any) -> Any: ...
    def __str__(self, /) -> Any: ...

class Domain:
    def __eq__(self, value, /) -> Any: ...
    def __ge__(self, value, /) -> Any: ...
    def __gt__(self, value, /) -> Any: ...
    def __hash__(self, /) -> Any: ...
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def __le__(self, value, /) -> Any: ...
    def __lt__(self, value, /) -> Any: ...
    def __ne__(self, value, /) -> Any: ...
    def __repr__(*args: Any, **kwargs: Any) -> Any: ...
    def __str__(self, /) -> Any: ...
    global_: Any = ...
    type: Any = ...
    units: Any = ...

class Field:
    def __eq__(self, value, /) -> Any: ...
    def __ge__(self, value, /) -> Any: ...
    def __gt__(self, value, /) -> Any: ...
    def __hash__(self, /) -> Any: ...
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def __le__(self, value, /) -> Any: ...
    def __lt__(self, value, /) -> Any: ...
    def __ne__(self, value, /) -> Any: ...
    def __repr__(self, /) -> Any: ...
    def __str__(self, /) -> Any: ...
    datatype: Any = ...
    metadata: Any = ...
    name: Any = ...
    rank: Any = ...
    shape: Any = ...
    size: Any = ...
    strides: Any = ...

class GaussianSpacing:
    def __eq__(self, value, /) -> Any: ...
    def __ge__(self, value, /) -> Any: ...
    def __getitem__(*args: Any, **kwargs: Any) -> Any: ...
    def __gt__(self, value, /) -> Any: ...
    def __hash__(self, /) -> Any: ...
    def __init__(*args: Any, **kwargs: Any) -> Any: ...
    def __le__(self, value, /) -> Any: ...
    def __len__(*args: Any, **kwargs: Any) -> Any: ...
    def __lt__(self, value, /) -> Any: ...
    def __ne__(self, value, /) -> Any: ...
    def __repr__(*args: Any, **kwargs: Any) -> Any: ...
    def __str__(self, /) -> Any: ...

class Gmsh:
    def __enter__(*args: Any, **kwargs: Any) -> Any: ...
    def __eq__(self, value, /) -> Any: ...
    def __exit__(*args: Any, **kwargs: Any) -> Any: ...
    def __ge__(self, value, /) -> Any: ...
    def __gt__(self, value, /) -> Any: ...
    def __hash__(self, /) -> Any: ...
    def __init__(*args: Any, **kwargs: Any) -> Any: ...
    def __le__(self, value, /) -> Any: ...
    def __lt__(self, value, /) -> Any: ...
    def __ne__(self, value, /) -> Any: ...
    def __repr__(self, /) -> Any: ...
    def __str__(self, /) -> Any: ...
    def write(*args: Any, **kwargs: Any) -> Any: ...

class Grid:
    def __eq__(self, value, /) -> Any: ...
    def __ge__(self, value, /) -> Any: ...
    def __gt__(self, value, /) -> Any: ...
    def __hash__(self, /) -> Any: ...
    def __init__(*args: Any, **kwargs: Any) -> Any: ...
    def __le__(self, value, /) -> Any: ...
    def __lt__(self, value, /) -> Any: ...
    def __ne__(self, value, /) -> Any: ...
    def __repr__(*args: Any, **kwargs: Any) -> Any: ...
    def __str__(self, /) -> Any: ...
    domain: Any = ...
    name: Any = ...
    projection: Any = ...
    size: Any = ...
    uid: Any = ...

class HybridElements:
    def __eq__(self, value, /) -> Any: ...
    def __ge__(self, value, /) -> Any: ...
    def __gt__(self, value, /) -> Any: ...
    def __hash__(self, /) -> Any: ...
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def __le__(self, value, /) -> Any: ...
    def __lt__(self, value, /) -> Any: ...
    def __ne__(self, value, /) -> Any: ...
    def __repr__(self, /) -> Any: ...
    def __str__(self, /) -> Any: ...
    cell_connectivity: Any = ...
    edge_connectivity: Any = ...
    def field(*args: Any, **kwargs: Any) -> Any: ...
    def flags(*args: Any, **kwargs: Any) -> Any: ...
    def nb_edges(*args: Any, **kwargs: Any) -> Any: ...
    def nb_nodes(*args: Any, **kwargs: Any) -> Any: ...
    node_connectivity: Any = ...
    size: Any = ...

class IrregularConnectivity:
    def __eq__(self, value, /) -> Any: ...
    def __ge__(self, value, /) -> Any: ...
    def __getitem__(*args: Any, **kwargs: Any) -> Any: ...
    def __gt__(self, value, /) -> Any: ...
    def __hash__(self, /) -> Any: ...
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def __le__(self, value, /) -> Any: ...
    def __lt__(self, value, /) -> Any: ...
    def __ne__(self, value, /) -> Any: ...
    def __repr__(self, /) -> Any: ...
    def __str__(self, /) -> Any: ...
    def cols(*args: Any, **kwargs: Any) -> Any: ...
    maxcols: Any = ...
    mincols: Any = ...
    rows: Any = ...

class LinearSpacing:
    def __eq__(self, value, /) -> Any: ...
    def __ge__(self, value, /) -> Any: ...
    def __getitem__(*args: Any, **kwargs: Any) -> Any: ...
    def __gt__(self, value, /) -> Any: ...
    def __hash__(self, /) -> Any: ...
    def __init__(*args: Any, **kwargs: Any) -> Any: ...
    def __le__(self, value, /) -> Any: ...
    def __len__(*args: Any, **kwargs: Any) -> Any: ...
    def __lt__(self, value, /) -> Any: ...
    def __ne__(self, value, /) -> Any: ...
    def __repr__(*args: Any, **kwargs: Any) -> Any: ...
    def __str__(self, /) -> Any: ...

class Mesh:
    def __eq__(self, value, /) -> Any: ...
    def __ge__(self, value, /) -> Any: ...
    def __gt__(self, value, /) -> Any: ...
    def __hash__(self, /) -> Any: ...
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def __le__(self, value, /) -> Any: ...
    def __lt__(self, value, /) -> Any: ...
    def __ne__(self, value, /) -> Any: ...
    def __repr__(self, /) -> Any: ...
    def __str__(self, /) -> Any: ...
    cells: Any = ...
    edges: Any = ...
    grid: Any = ...
    nodes: Any = ...
    projection: Any = ...

class Metadata:
    def __eq__(self, value, /) -> Any: ...
    def __ge__(self, value, /) -> Any: ...
    def __getitem__(*args: Any, **kwargs: Any) -> Any: ...
    def __gt__(self, value, /) -> Any: ...
    def __hash__(self, /) -> Any: ...
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def __le__(self, value, /) -> Any: ...
    def __lt__(self, value, /) -> Any: ...
    def __ne__(self, value, /) -> Any: ...
    def __repr__(*args: Any, **kwargs: Any) -> Any: ...
    def __setitem__(*args: Any, **kwargs: Any) -> Any: ...
    def __str__(self, /) -> Any: ...
    keys: Any = ...

class MultiBlockConnectivity:
    def __eq__(self, value, /) -> Any: ...
    def __ge__(self, value, /) -> Any: ...
    def __getitem__(*args: Any, **kwargs: Any) -> Any: ...
    def __gt__(self, value, /) -> Any: ...
    def __hash__(self, /) -> Any: ...
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def __le__(self, value, /) -> Any: ...
    def __lt__(self, value, /) -> Any: ...
    def __ne__(self, value, /) -> Any: ...
    def __repr__(self, /) -> Any: ...
    def __str__(self, /) -> Any: ...
    def block(*args: Any, **kwargs: Any) -> Any: ...
    blocks: Any = ...
    def cols(*args: Any, **kwargs: Any) -> Any: ...
    maxcols: Any = ...
    mincols: Any = ...
    rows: Any = ...

class Nodes:
    def __eq__(self, value, /) -> Any: ...
    def __ge__(self, value, /) -> Any: ...
    def __gt__(self, value, /) -> Any: ...
    def __hash__(self, /) -> Any: ...
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def __le__(self, value, /) -> Any: ...
    def __lt__(self, value, /) -> Any: ...
    def __ne__(self, value, /) -> Any: ...
    def __repr__(self, /) -> Any: ...
    def __str__(self, /) -> Any: ...
    cell_connectivity: Any = ...
    edge_connectivity: Any = ...
    def field(*args: Any, **kwargs: Any) -> Any: ...
    def flags(*args: Any, **kwargs: Any) -> Any: ...
    lonlat: Any = ...
    size: Any = ...

class PointLonLat:
    def __eq__(self, value, /) -> Any: ...
    def __ge__(self, value, /) -> Any: ...
    def __gt__(self, value, /) -> Any: ...
    def __hash__(self, /) -> Any: ...
    def __init__(*args: Any, **kwargs: Any) -> Any: ...
    def __le__(self, value, /) -> Any: ...
    def __lt__(self, value, /) -> Any: ...
    def __ne__(self, value, /) -> Any: ...
    def __repr__(*args: Any, **kwargs: Any) -> Any: ...
    def __str__(self, /) -> Any: ...
    lat: Any = ...
    lon: Any = ...

class PointXY:
    def __eq__(self, value, /) -> Any: ...
    def __ge__(self, value, /) -> Any: ...
    def __gt__(self, value, /) -> Any: ...
    def __hash__(self, /) -> Any: ...
    def __init__(*args: Any, **kwargs: Any) -> Any: ...
    def __le__(self, value, /) -> Any: ...
    def __lt__(self, value, /) -> Any: ...
    def __ne__(self, value, /) -> Any: ...
    def __repr__(*args: Any, **kwargs: Any) -> Any: ...
    def __str__(self, /) -> Any: ...
    x: Any = ...
    y: Any = ...

class Projection:
    def __eq__(self, value, /) -> Any: ...
    def __ge__(self, value, /) -> Any: ...
    def __gt__(self, value, /) -> Any: ...
    def __hash__(self, /) -> Any: ...
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def __le__(self, value, /) -> Any: ...
    def __lt__(self, value, /) -> Any: ...
    def __ne__(self, value, /) -> Any: ...
    def __repr__(*args: Any, **kwargs: Any) -> Any: ...
    def __str__(self, /) -> Any: ...

class RectangularDomain:
    def __eq__(self, value, /) -> Any: ...
    def __ge__(self, value, /) -> Any: ...
    def __gt__(self, value, /) -> Any: ...
    def __hash__(self, /) -> Any: ...
    def __init__(*args: Any, **kwargs: Any) -> Any: ...
    def __le__(self, value, /) -> Any: ...
    def __lt__(self, value, /) -> Any: ...
    def __ne__(self, value, /) -> Any: ...
    def __repr__(*args: Any, **kwargs: Any) -> Any: ...
    def __str__(self, /) -> Any: ...
    global_: Any = ...
    type: Any = ...
    units: Any = ...

class Spacing:
    def __eq__(self, value, /) -> Any: ...
    def __ge__(self, value, /) -> Any: ...
    def __getitem__(*args: Any, **kwargs: Any) -> Any: ...
    def __gt__(self, value, /) -> Any: ...
    def __hash__(self, /) -> Any: ...
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def __le__(self, value, /) -> Any: ...
    def __len__(*args: Any, **kwargs: Any) -> Any: ...
    def __lt__(self, value, /) -> Any: ...
    def __ne__(self, value, /) -> Any: ...
    def __repr__(*args: Any, **kwargs: Any) -> Any: ...
    def __str__(self, /) -> Any: ...

class StructuredGrid:
    def __eq__(self, value, /) -> Any: ...
    def __ge__(self, value, /) -> Any: ...
    def __gt__(self, value, /) -> Any: ...
    def __hash__(self, /) -> Any: ...
    def __init__(*args: Any, **kwargs: Any) -> Any: ...
    def __le__(self, value, /) -> Any: ...
    def __lt__(self, value, /) -> Any: ...
    def __ne__(self, value, /) -> Any: ...
    def __repr__(*args: Any, **kwargs: Any) -> Any: ...
    def __str__(self, /) -> Any: ...
    domain: Any = ...
    def lonlat(*args: Any, **kwargs: Any) -> Any: ...
    name: Any = ...
    nx: Any = ...
    nxmax: Any = ...
    ny: Any = ...
    periodic: Any = ...
    projection: Any = ...
    reduced: Any = ...
    regular: Any = ...
    size: Any = ...
    uid: Any = ...
    valid: Any = ...
    x: Any = ...
    def xy(*args: Any, **kwargs: Any) -> Any: ...
    y: Any = ...

class StructuredMeshGenerator:
    def __eq__(self, value, /) -> Any: ...
    def __ge__(self, value, /) -> Any: ...
    def __gt__(self, value, /) -> Any: ...
    def __hash__(self, /) -> Any: ...
    def __init__(*args: Any, **kwargs: Any) -> Any: ...
    def __le__(self, value, /) -> Any: ...
    def __lt__(self, value, /) -> Any: ...
    def __ne__(self, value, /) -> Any: ...
    def __repr__(self, /) -> Any: ...
    def __str__(self, /) -> Any: ...
    def generate(*args: Any, **kwargs: Any) -> Any: ...

class Topology:
    BC: Any = ...
    EAST: Any = ...
    GHOST: Any = ...
    NONE: Any = ...
    NORTH: Any = ...
    PATCH: Any = ...
    PERIODIC: Any = ...
    POLE: Any = ...
    SOUTH: Any = ...
    WEST: Any = ...
    def __eq__(self, value, /) -> Any: ...
    def __ge__(self, value, /) -> Any: ...
    def __gt__(self, value, /) -> Any: ...
    def __hash__(self, /) -> Any: ...
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def __le__(self, value, /) -> Any: ...
    def __lt__(self, value, /) -> Any: ...
    def __ne__(self, value, /) -> Any: ...
    def __repr__(self, /) -> Any: ...
    def __str__(self, /) -> Any: ...
    def check(*args: Any, **kwargs: Any) -> Any: ...
    def check_all(*args: Any, **kwargs: Any) -> Any: ...
    def check_any(*args: Any, **kwargs: Any) -> Any: ...
    def reset(*args: Any, **kwargs: Any) -> Any: ...
    def set(*args: Any, **kwargs: Any) -> Any: ...
    def toggle(*args: Any, **kwargs: Any) -> Any: ...
    def unset(*args: Any, **kwargs: Any) -> Any: ...

atexit: Any = ...

def build_edges(*args: Any, **kwargs: Any) -> Any: ...
def build_element_to_edge_connectivity(*args: Any, **kwargs: Any) -> Any: ...
def build_halo(*args: Any, **kwargs: Any) -> Any: ...
def build_median_dual_mesh(*args: Any, **kwargs: Any) -> Any: ...
def build_node_to_cell_connectivity(*args: Any, **kwargs: Any) -> Any: ...
def build_node_to_edge_connectivity(*args: Any, **kwargs: Any) -> Any: ...
def build_parallel_fields(*args: Any, **kwargs: Any) -> Any: ...
def build_periodic_boundaries(*args: Any, **kwargs: Any) -> Any: ...

class eckit:
    class Configuration:
        def __eq__(self, value, /) -> Any: ...
        def __ge__(self, value, /) -> Any: ...
        def __gt__(self, value, /) -> Any: ...
        def __hash__(self, /) -> Any: ...
        def __init__(self, /, *args, **kwargs) -> Any: ...
        def __le__(self, value, /) -> Any: ...
        def __lt__(self, value, /) -> Any: ...
        def __ne__(self, value, /) -> Any: ...
        def __repr__(self, /) -> Any: ...
        def __str__(self, /) -> Any: ...

    class LocalConfiguration:
        def __eq__(self, value, /) -> Any: ...
        def __ge__(self, value, /) -> Any: ...
        def __gt__(self, value, /) -> Any: ...
        def __hash__(self, /) -> Any: ...
        def __init__(self, /, *args, **kwargs) -> Any: ...
        def __le__(self, value, /) -> Any: ...
        def __lt__(self, value, /) -> Any: ...
        def __ne__(self, value, /) -> Any: ...
        def __repr__(self, /) -> Any: ...
        def __str__(self, /) -> Any: ...

functionspace: Any = ...
version: Any = ...
