name: Daily checks

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  daily-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'
        cache-dependency-path: |
          **/setup.cfg
          **/constraints.txt
          **/requirements-dev.txt
    - name: Install dependencies
      run: |
        python -m pip install -c ./constraints.txt pip setuptools wheel
        python -m pip install -c ./constraints.txt tox
    - name: Run checks
      run: |
        python -m pip list
        tox run -e requirements
        tox run -e eve-py310

