name: Eve / Coverage

on:
  workflow_run:
    workflows: ["Eve / Test"]
    types:
    - completed

jobs:
  upload:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/template_coverage.yml
    with:
      workflow_run_id: ${{ github.event.workflow_run.id }}
      coverage_flag: eve-all
    secrets: inherit
