name: "Eve / Test"

on:
  push:
    branches:
    - functional
    paths: # Run only when eve sources or tests have changed.
    - "**"
    - "!src/**"
    - "!tests/**"
    - "src/eve"
    - "tests/eve_tests"
  pull_request:
    branches:
    - functional
    paths: # Run only when eve sources or tests have changed.
    - "**"
    - "!src/**"
    - "!tests/**"
    - "src/eve"
    - "tests/eve_tests"

jobs:
  tox:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: ["ubuntu-latest"]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
    - name: Run tox tests
      run: |
        pyversion_no_dot="${{ matrix.python-version }}"
        pyversion_no_dot="${pyversion_no_dot/./}"
        pip install tox
        tox -r -e eve-py${pyversion_no_dot}
        mv coverage.json coverage-py${{ matrix.python-version }}-${{ matrix.os }}.json
    - name: Upload coverage.json artifact
      uses: actions/upload-artifact@v3
      with:
        name: coverage-py${{ matrix.python-version }}-${{ matrix.os }}
        path: coverage-py${{ matrix.python-version }}-${{ matrix.os }}.json
    - name: Gather info
      run: |
        echo ${{ github.ref_type }} >> info.txt
        echo ${{ github.ref }} >> info.txt
        echo ${{ github.sha }} >> info.txt
        echo ${{ github.event.number }} >> info.txt
        echo ${{ github.event.pull_request.head.ref }} >> info.txt
        echo ${{ github.event.pull_request.head.sha }} >> info.txt
        echo ${{ github.run_id }} >> info.txt
    - name: Upload info artifact
      uses: actions/upload-artifact@v3
      with:
        name: info-py${{ matrix.python-version }}-${{ matrix.os }}
        path: info.txt

