name: Eve / Test

on:
  push:
    branches:
    - functional
    paths:
    - "**"
    - "!src/**"
    - "!tests/**"
    - "src/eve"
    - "tests/eve_tests"
  pull_request:
    branches:
    - functional
    paths:
    - "**"
    - "!src/**"
    - "!tests/**"
    - "src/eve"
    - "tests/eve_tests"

jobs:
  tox:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: ["ubuntu-latest", "macos-latest"]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
    - name: Run tox tests
      run: |
        pyversion_no_dot="${{ matrix.python-version }}"
        pyversion_no_dot="${pyversion_no_dot/./}"
        pip install tox
        tox -r -e eve-py${pyversion_no_dot}
