name: Eve / Coverage

on:
  push:
    branches:
    - functional
    - ci-test-branch
    paths: # Run only when eve sources or tests have changed.
    - "**"
    - "!src/**"
    - "!tests/**"
    - "src/eve"
    - "tests/eve_tests"
  pull_request:
    branches:
    - functional
    - ci-test-branch
    paths: # Run only when eve sources or tests have changed.
    - "**"
    - "!src/**"
    - "!tests/**"
    - "src/eve"
    - "tests/eve_tests"

jobs:
  collect:
    runs-on: ubuntu-latest
    env:
      PY_VERSION: "3.10"
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ env.PY_VERSION }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PY_VERSION }}

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel

    - name: Gather coverage
      run: |
        pyversion_no_dot="${{ env.PY_VERSION }}"
        pyversion_no_dot="${pyversion_no_dot/./}"
        pip install tox
        tox -r -e eve-py${pyversion_no_dot}

    - name: Upload coverage.xml artifact
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: coverage.json

    - name: Upload to codecov.io
      uses: codecov/codecov-action@v2
      with:
        files: coverage.json
        fail_ci_if_error: true
        flags: eve-all
        token: ${{ secrets.CODECOV_TOKEN }}
