name: Gt4py / Test

# gt4py tests must run even if only eve is changed and gt4py is unchanged.
on:
  push:
    branches:
    - functional
  pull_request:
    branches:
    - functional

jobs:
  tox:
    strategy:
      matrix:
        python-version: ["3.10"]
        tox-env-factors: ["base", "atlas"]
        os: ["ubuntu-latest", "macos-latest"]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Install C++ libraries
      if: ${{ matrix.os }} == "macos-latest"
      shell: bash
      run: |
        brew install boost
    - name: Install C++ libraries
      if: ${{ matrix.os }} == "ubuntu-latest"
      shell: bash
      run: |
        sudo apt install libboost-dev
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install python dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip setuptools wheel
    - name: Run tox tests
      shell: bash
      run: |
        pyversion_no_dot="${{ matrix.python-version }}"
        pyversion_no_dot="${pyversion_no_dot/./}"
        tox_env_factor="${{ matrix.tox-env-factors }}"
        pip install tox clang-format
        tox -r -e gt4py-py${pyversion_no_dot}-${tox_env_factor}
