name: Gt4py / Test

# gt4py tests must run even if only eve is changed and gt4py is unchanged.
on:
  push:
    branches:
    - functional
    - ci-test-branch
    # Run on any file change.
  pull_request:
    branches:
    - functional
    - ci-test-branch
    # Run on any file change.

jobs:
  tox:
    strategy:
      matrix:
        python-version: ["3.10"]
        tox-env-factors: ["base", "atlas"]
        os: ["ubuntu-latest", "macos-latest"]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Install C++ libraries
      if: ${{ matrix.os == 'macos-latest' }}
      shell: bash
      run: |
        brew install boost
    - name: Install C++ libraries
      if: ${{ matrix.os == 'ubuntu-latest' }}
      shell: bash
      run: |
        sudo apt install libboost-dev
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install python dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip setuptools wheel
    - name: Run tox tests
      shell: bash
      run: |
        pyversion_no_dot="${{ matrix.python-version }}"
        pyversion_no_dot="${pyversion_no_dot/./}"
        tox_env_factor="${{ matrix.tox-env-factors }}"
        pip install tox clang-format
        tox -r -e gt4py-py${pyversion_no_dot}-${tox_env_factor}
    - name: Upload coverage.json artifact
      uses: actions/upload-artifact@v3
      with:
        name: coverage-py${{ matrix.python-version }}-${{ matrix.os }}-{{ matrix.tox_env_factor }}
        path: coverage-py${{ matrix.python-version }}-${{ matrix.os }}-{{ matrix.tox_env_factor }}.json
    - name: Gather info
      env:
        PR_NUMBER: ${{ github.event.number }}
      run: |
        echo ${{ env.PR_NUMBER }} >> info-py${{ matrix.python-version }}-${{ matrix.os }}-{{ matrix.tox_env_factor }}.txt
    - name: Upload info artifact
      uses: actions/upload-artifact@v3
      with:
        name: info-py${{ matrix.python-version }}-${{ matrix.os }}-{{ matrix.tox_env_factor }}
        path: info-py${{ matrix.python-version }}-${{ matrix.os }}-{{ matrix.tox_env_factor }}.txt
