name: Gt4py / Coverage

on:
  push:
    branches:
    - functional
    - ci-test-branch
    paths: # Run only when gt4py sources or tests have changed.
    - "**"
    - "!src/**"
    - "!tests/**"
    - "src/functional"
    - "tests/functional_tests"
  pull_request:
    branches:
    - functional
    - ci-test-branch
    paths: # Run only when gt4py sources or tests have changed.
    - "**"
    - "!src/**"
    - "!tests/**"
    - "src/functional"
    - "tests/functional_tests"

jobs:
  collect:
    runs-on: ubuntu-latest
    env:
      PY_VERSION: "3.10"
      TOX_ENV_FACTOR: "base"
    steps:
    - uses: actions/checkout@v2

    - name: Install C++ libraries
      shell: bash
      run: |
        sudo apt install libboost-dev

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PY_VERSION }}

    - name: Install python dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip setuptools wheel

    - name: Gather coverage
      shell: bash
      run: |
        pyversion_no_dot="${{ env.PY_VERSION }}"
        pyversion_no_dot="${pyversion_no_dot/./}"
        tox_env_factor="${{ env.TOX_ENV_FACTOR }}"
        pip install tox clang-format
        tox -r -e gt4py-py${pyversion_no_dot}-${tox_env_factor}

    - name: Upload coverage.xml artifact
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: coverage.json

    - name: Upload to codecov.io
      uses: codecov/codecov-action@v2
      with:
        files: coverage.json
        fail_ci_if_error: true
        flags: gt4py-all
        token: ${{ secrets.CODECOV_TOKEN }}
