name: CI
on:
  push:
    branches:
    - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: mirror-repository
      run: |
        mkdir ~/.ssh
        echo "${GIT_SSH_PRIVATE_KEY}" > ~/.ssh/id_ed
        chmod 600 ~/.ssh/id_ed
        export GIT_SSH_COMMAND="ssh -i ~/.ssh/id_ed -o IdentitiesOnly=yes -o StrictHostKeyChecking=no"
        git remote add mirror "${REMOTE}"
        git remote show mirror
        git push --tags --force --prune mirror 'refs/remotes/origin/*:refs/heads/*'
      env:
        REMOTE: git@gitlab.com:cscs-ci/gridtools/gt4py.git
        GIT_SSH_PRIVATE_KEY: ${{ secrets.MIRROR_SSH_KEY }}
