name: "Skipped: Test / Next (CPU)"

on:
  pull_request:
    branches:
    - main
    paths: # inverse of corresponding workflow
    - "src/gt4py/cartesian/**"
    - "tests/cartesian_tests/**"

jobs:
  test-next:
    strategy:
      matrix:
        python-version: ["3.10"]
        tox-env-factor: ["nomesh", "atlas"]
        os: ["ubuntu-latest"]

    runs-on: ${{ matrix.os }}
    steps:
    - run: 'echo "No build required"'
