name: Tests

on:
  push:
    branches:
    - functional
  pull_request:
    branches:
    - functional

jobs:
  tox-tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        tox-env-factors: ["base", "atlas"]
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install python dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip setuptools wheel

    - name: Test using tox
      shell: bash
      run: |
        pyversion_no_dot="${{ matrix.python-version }}"
        pyversion_no_dot="${pyversion_no_dot/./}"
        tox_env_factor="${{ matrix.tox-env-factors }}"
        pip install tox clang-format
        tox -r -e py${pyversion_no_dot}-${tox_env_factor}

    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: tests/_reports/
